apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.component }}
  labels:
    appName: {{ .Values.component }}
    projectName: {{ .Chart.Name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      appName: {{ .Values.component }}
      projectName: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        appName: {{ .Values.component }}
        projectName: {{ .Chart.Name }}
    spec:
      {{ if .Values.initContainers.enabled }}
      volumes:
        - name: vault
          emptyDir:
            sizeLimit: 5Mi
      initContainers:
        - name: vault
          image: 368761340104.dkr.ecr.us-east-1.amazonaws.com/vault-init-container:v2
          imagePullPolicy: Always
          env:
            - name: VAULT_ADDR
              value: "https://vault-internal.ramdevops78.online:8200"
            - name: VAULT_SKIP_VERIFY
              value: "TRUE"
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-token
                  key: token
            - name: SECRET_NAME
              value: {{ .Chart.Name }}-dev/{{ .Values.component }}
          volumeMounts:
              - name: vault
                mountPath: /data
        - name: schema
          image: 368761340104.dkr.ecr.us-east-1.amazonaws.com/schema-init-container:v2
          imagePullPolicy: Always
          volumeMounts:
            - name: vault
              mountPath: /data
      {{ end }}
      containers:
        - name: {{ .Values.component }}
          image: 368761340104.dkr.ecr.us-east-1.amazonaws.com/{{ .Chart.Name }}-{{ .Values.component }}:{{ .Values.appVersion }}
          imagePullPolicy: Always
          command: ["sleep", "1000"]
      {{ if .Values.initContainers.enabled }}
      volumeMounts:
        - name: vault
          mountPath: /data
      {{ end }}
    


