apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    appName: backend
    projectName: expense
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080