apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.component }}
spec:
  selector:
    type: {{ .Values.service.type}}
    appName: {{ .Values.component }}
    projectName: {{ .Chart.Name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.targetPort }}